// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositoryIMPL

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TPerfi struct {
	ID           int32
	Nome         string
	Descricao    string
	Ativo        pgtype.Bool
	AtualizadoEm pgtype.Timestamptz
}

type TPerfilPermissao struct {
	ID          int32
	PerfilID    int32
	PermissaoID int32
	DataHora    pgtype.Timestamp
}

type TPermisso struct {
	ID           int32
	Nome         string
	Descricao    string
	Ativo        pgtype.Bool
	AtualizadoEm pgtype.Timestamptz
}

type TUsuarioPerfil struct {
	ID               int32
	UsuarioInternoID pgtype.Int4
	UsuarioExternoID pgtype.Int4
	PerfilID         int32
	DataHora         pgtype.Timestamp
}

type TUsuariosExterno struct {
	ID              int32
	Uuid            pgtype.Text
	IDExterno       int32
	Nome            string
	Email           string
	Senha           string
	Documento       string
	CodReserva      pgtype.Text
	Ativo           pgtype.Bool
	AtualizadoEm    pgtype.Timestamptz
	TokenResetSenha pgtype.Text
	SenhaAtualizada pgtype.Bool
}

type TUsuariosInterno struct {
	ID              int32
	Nome            string
	Email           string
	Senha           string
	Ativo           pgtype.Bool
	TokenResetSenha pgtype.Text
	AtualizadoEm    pgtype.Timestamptz
	SenhaAtualizada pgtype.Bool
}
