// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: modelos.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definição do modelo de UsuarioExterno
type UsuarioExterno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid            string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IdExterno       int32  `protobuf:"varint,3,opt,name=idExterno,proto3" json:"idExterno,omitempty"`
	Nome            string `protobuf:"bytes,4,opt,name=nome,proto3" json:"nome,omitempty"`
	Documento       string `protobuf:"bytes,5,opt,name=documento,proto3" json:"documento,omitempty"`
	Email           string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Senha           string `protobuf:"bytes,7,opt,name=senha,proto3" json:"senha,omitempty"`
	CodReserva      string `protobuf:"bytes,8,opt,name=codReserva,proto3" json:"codReserva,omitempty"`
	Ativo           bool   `protobuf:"varint,9,opt,name=ativo,proto3" json:"ativo,omitempty"`
	TokenResetSenha string `protobuf:"bytes,10,opt,name=tokenResetSenha,proto3" json:"tokenResetSenha,omitempty"`
	AtualizadoEm    string `protobuf:"bytes,11,opt,name=atualizadoEm,proto3" json:"atualizadoEm,omitempty"`
	SenhaAtualizada bool   `protobuf:"varint,12,opt,name=senhaAtualizada,proto3" json:"senhaAtualizada,omitempty"`
}

func (x *UsuarioExterno) Reset() {
	*x = UsuarioExterno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioExterno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioExterno) ProtoMessage() {}

func (x *UsuarioExterno) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioExterno.ProtoReflect.Descriptor instead.
func (*UsuarioExterno) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{0}
}

func (x *UsuarioExterno) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsuarioExterno) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UsuarioExterno) GetIdExterno() int32 {
	if x != nil {
		return x.IdExterno
	}
	return 0
}

func (x *UsuarioExterno) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UsuarioExterno) GetDocumento() string {
	if x != nil {
		return x.Documento
	}
	return ""
}

func (x *UsuarioExterno) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UsuarioExterno) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *UsuarioExterno) GetCodReserva() string {
	if x != nil {
		return x.CodReserva
	}
	return ""
}

func (x *UsuarioExterno) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *UsuarioExterno) GetTokenResetSenha() string {
	if x != nil {
		return x.TokenResetSenha
	}
	return ""
}

func (x *UsuarioExterno) GetAtualizadoEm() string {
	if x != nil {
		return x.AtualizadoEm
	}
	return ""
}

func (x *UsuarioExterno) GetSenhaAtualizada() bool {
	if x != nil {
		return x.SenhaAtualizada
	}
	return false
}

// Definição do modelo de Perfis
type Perfil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome         string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao    string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Ativo        bool   `protobuf:"varint,4,opt,name=ativo,proto3" json:"ativo,omitempty"`
	AtualizadoEm string `protobuf:"bytes,5,opt,name=atualizadoEm,proto3" json:"atualizadoEm,omitempty"`
}

func (x *Perfil) Reset() {
	*x = Perfil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Perfil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perfil) ProtoMessage() {}

func (x *Perfil) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perfil.ProtoReflect.Descriptor instead.
func (*Perfil) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{1}
}

func (x *Perfil) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Perfil) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Perfil) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Perfil) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Perfil) GetAtualizadoEm() string {
	if x != nil {
		return x.AtualizadoEm
	}
	return ""
}

// Definição do modelo de Permissões
type Permissao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome         string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao    string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Ativo        bool   `protobuf:"varint,4,opt,name=ativo,proto3" json:"ativo,omitempty"`
	AtualizadoEm string `protobuf:"bytes,5,opt,name=atualizadoEm,proto3" json:"atualizadoEm,omitempty"`
}

func (x *Permissao) Reset() {
	*x = Permissao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissao) ProtoMessage() {}

func (x *Permissao) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissao.ProtoReflect.Descriptor instead.
func (*Permissao) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{2}
}

func (x *Permissao) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permissao) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Permissao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Permissao) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Permissao) GetAtualizadoEm() string {
	if x != nil {
		return x.AtualizadoEm
	}
	return ""
}

// Definição do modelo de relação entre Perfil e Permissões
type PerfilPermissoes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perfil     *Perfil      `protobuf:"bytes,1,opt,name=perfil,proto3" json:"perfil,omitempty"`
	Permissoes []*Permissao `protobuf:"bytes,2,rep,name=permissoes,proto3" json:"permissoes,omitempty"`
}

func (x *PerfilPermissoes) Reset() {
	*x = PerfilPermissoes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfilPermissoes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilPermissoes) ProtoMessage() {}

func (x *PerfilPermissoes) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilPermissoes.ProtoReflect.Descriptor instead.
func (*PerfilPermissoes) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{3}
}

func (x *PerfilPermissoes) GetPerfil() *Perfil {
	if x != nil {
		return x.Perfil
	}
	return nil
}

func (x *PerfilPermissoes) GetPermissoes() []*Permissao {
	if x != nil {
		return x.Permissoes
	}
	return nil
}

// Definição do modelo de UsuarioInterno
type UsuarioInterno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome            string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Email           string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Senha           string `protobuf:"bytes,4,opt,name=senha,proto3" json:"senha,omitempty"`
	Ativo           bool   `protobuf:"varint,5,opt,name=ativo,proto3" json:"ativo,omitempty"`
	TokenResetSenha string `protobuf:"bytes,6,opt,name=tokenResetSenha,proto3" json:"tokenResetSenha,omitempty"`
	AtualizadoEm    string `protobuf:"bytes,7,opt,name=atualizadoEm,proto3" json:"atualizadoEm,omitempty"`
	SenhaAtualizada bool   `protobuf:"varint,8,opt,name=senhaAtualizada,proto3" json:"senhaAtualizada,omitempty"`
}

func (x *UsuarioInterno) Reset() {
	*x = UsuarioInterno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioInterno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioInterno) ProtoMessage() {}

func (x *UsuarioInterno) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioInterno.ProtoReflect.Descriptor instead.
func (*UsuarioInterno) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{4}
}

func (x *UsuarioInterno) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsuarioInterno) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UsuarioInterno) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UsuarioInterno) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *UsuarioInterno) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *UsuarioInterno) GetTokenResetSenha() string {
	if x != nil {
		return x.TokenResetSenha
	}
	return ""
}

func (x *UsuarioInterno) GetAtualizadoEm() string {
	if x != nil {
		return x.AtualizadoEm
	}
	return ""
}

func (x *UsuarioInterno) GetSenhaAtualizada() bool {
	if x != nil {
		return x.SenhaAtualizada
	}
	return false
}

// Definição do modelo de relação entre Usuário e Perfis
type UsuarioPerfis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioInterno *UsuarioInterno `protobuf:"bytes,1,opt,name=usuarioInterno,proto3" json:"usuarioInterno,omitempty"`
	UsuarioExterno *UsuarioExterno `protobuf:"bytes,2,opt,name=usuarioExterno,proto3" json:"usuarioExterno,omitempty"`
	Perfis         []*Perfil       `protobuf:"bytes,3,rep,name=perfis,proto3" json:"perfis,omitempty"`
}

func (x *UsuarioPerfis) Reset() {
	*x = UsuarioPerfis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioPerfis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioPerfis) ProtoMessage() {}

func (x *UsuarioPerfis) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioPerfis.ProtoReflect.Descriptor instead.
func (*UsuarioPerfis) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{5}
}

func (x *UsuarioPerfis) GetUsuarioInterno() *UsuarioInterno {
	if x != nil {
		return x.UsuarioInterno
	}
	return nil
}

func (x *UsuarioPerfis) GetUsuarioExterno() *UsuarioExterno {
	if x != nil {
		return x.UsuarioExterno
	}
	return nil
}

func (x *UsuarioPerfis) GetPerfis() []*Perfil {
	if x != nil {
		return x.Perfis
	}
	return nil
}

// Definição do modelo de relação entre Perfil e Usuários
type PerfilUsuarios struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perfil           *Perfil           `protobuf:"bytes,1,opt,name=perfil,proto3" json:"perfil,omitempty"`
	UsuariosInternos []*UsuarioInterno `protobuf:"bytes,2,rep,name=usuariosInternos,proto3" json:"usuariosInternos,omitempty"`
	UsuariosExternos []*UsuarioExterno `protobuf:"bytes,3,rep,name=usuariosExternos,proto3" json:"usuariosExternos,omitempty"`
}

func (x *PerfilUsuarios) Reset() {
	*x = PerfilUsuarios{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfilUsuarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilUsuarios) ProtoMessage() {}

func (x *PerfilUsuarios) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilUsuarios.ProtoReflect.Descriptor instead.
func (*PerfilUsuarios) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{6}
}

func (x *PerfilUsuarios) GetPerfil() *Perfil {
	if x != nil {
		return x.Perfil
	}
	return nil
}

func (x *PerfilUsuarios) GetUsuariosInternos() []*UsuarioInterno {
	if x != nil {
		return x.UsuariosInternos
	}
	return nil
}

func (x *PerfilUsuarios) GetUsuariosExternos() []*UsuarioExterno {
	if x != nil {
		return x.UsuariosExternos
	}
	return nil
}

// Definição do modelo de envio de e-mail para reset de senha
type EmailReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailReset) Reset() {
	*x = EmailReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReset) ProtoMessage() {}

func (x *EmailReset) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReset.ProtoReflect.Descriptor instead.
func (*EmailReset) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{7}
}

func (x *EmailReset) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Definição do modelo de Login dos usuários
type LoginUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Senha string `protobuf:"bytes,2,opt,name=senha,proto3" json:"senha,omitempty"`
}

func (x *LoginUsuario) Reset() {
	*x = LoginUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUsuario) ProtoMessage() {}

func (x *LoginUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUsuario.ProtoReflect.Descriptor instead.
func (*LoginUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{8}
}

func (x *LoginUsuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUsuario) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

// Definição do modelo de retorno da requisição de Login
type RetornoLoginUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome  string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Token string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RetornoLoginUsuario) Reset() {
	*x = RetornoLoginUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetornoLoginUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetornoLoginUsuario) ProtoMessage() {}

func (x *RetornoLoginUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetornoLoginUsuario.ProtoReflect.Descriptor instead.
func (*RetornoLoginUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{9}
}

func (x *RetornoLoginUsuario) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetornoLoginUsuario) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *RetornoLoginUsuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RetornoLoginUsuario) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetSenhaUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SenhaNova string `protobuf:"bytes,2,opt,name=senhaNova,proto3" json:"senhaNova,omitempty"`
}

func (x *ResetSenhaUsuario) Reset() {
	*x = ResetSenhaUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetSenhaUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSenhaUsuario) ProtoMessage() {}

func (x *ResetSenhaUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSenhaUsuario.ProtoReflect.Descriptor instead.
func (*ResetSenhaUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{10}
}

func (x *ResetSenhaUsuario) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetSenhaUsuario) GetSenhaNova() string {
	if x != nil {
		return x.SenhaNova
	}
	return ""
}

type RequestVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestVazio) Reset() {
	*x = RequestVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVazio) ProtoMessage() {}

func (x *RequestVazio) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVazio.ProtoReflect.Descriptor instead.
func (*RequestVazio) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{11}
}

type RequestId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestId) Reset() {
	*x = RequestId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestId) ProtoMessage() {}

func (x *RequestId) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestId.ProtoReflect.Descriptor instead.
func (*RequestId) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{12}
}

func (x *RequestId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alterado bool `protobuf:"varint,1,opt,name=alterado,proto3" json:"alterado,omitempty"`
}

func (x *ResponseBool) Reset() {
	*x = ResponseBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBool) ProtoMessage() {}

func (x *ResponseBool) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBool.ProtoReflect.Descriptor instead.
func (*ResponseBool) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseBool) GetAlterado() bool {
	if x != nil {
		return x.Alterado
	}
	return false
}

type RequestNome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome          string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	TamanhoPagina int32  `protobuf:"varint,2,opt,name=tamanhoPagina,proto3" json:"tamanhoPagina,omitempty"`
	Cursor        int32  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *RequestNome) Reset() {
	*x = RequestNome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNome) ProtoMessage() {}

func (x *RequestNome) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNome.ProtoReflect.Descriptor instead.
func (*RequestNome) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{14}
}

func (x *RequestNome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *RequestNome) GetTamanhoPagina() int32 {
	if x != nil {
		return x.TamanhoPagina
	}
	return 0
}

func (x *RequestNome) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type RequestCodReserva struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodReserva    string `protobuf:"bytes,1,opt,name=codReserva,proto3" json:"codReserva,omitempty"`
	TamanhoPagina int32  `protobuf:"varint,2,opt,name=tamanhoPagina,proto3" json:"tamanhoPagina,omitempty"`
	Cursor        int32  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *RequestCodReserva) Reset() {
	*x = RequestCodReserva{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCodReserva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCodReserva) ProtoMessage() {}

func (x *RequestCodReserva) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCodReserva.ProtoReflect.Descriptor instead.
func (*RequestCodReserva) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{15}
}

func (x *RequestCodReserva) GetCodReserva() string {
	if x != nil {
		return x.CodReserva
	}
	return ""
}

func (x *RequestCodReserva) GetTamanhoPagina() int32 {
	if x != nil {
		return x.TamanhoPagina
	}
	return 0
}

func (x *RequestCodReserva) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type RequestDocumento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documento string `protobuf:"bytes,1,opt,name=documento,proto3" json:"documento,omitempty"`
}

func (x *RequestDocumento) Reset() {
	*x = RequestDocumento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDocumento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDocumento) ProtoMessage() {}

func (x *RequestDocumento) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDocumento.ProtoReflect.Descriptor instead.
func (*RequestDocumento) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{16}
}

func (x *RequestDocumento) GetDocumento() string {
	if x != nil {
		return x.Documento
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProximoCursor int32 `protobuf:"varint,1,opt,name=proximoCursor,proto3" json:"proximoCursor,omitempty"`
	TamanhoPagina int32 `protobuf:"varint,2,opt,name=tamanhoPagina,proto3" json:"tamanhoPagina,omitempty"`
	TemMais       bool  `protobuf:"varint,3,opt,name=temMais,proto3" json:"temMais,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{17}
}

func (x *Meta) GetProximoCursor() int32 {
	if x != nil {
		return x.ProximoCursor
	}
	return 0
}

func (x *Meta) GetTamanhoPagina() int32 {
	if x != nil {
		return x.TamanhoPagina
	}
	return 0
}

func (x *Meta) GetTemMais() bool {
	if x != nil {
		return x.TemMais
	}
	return false
}

type RequestAllPaginado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TamanhoPagina int32 `protobuf:"varint,1,opt,name=tamanhoPagina,proto3" json:"tamanhoPagina,omitempty"`
	Cursor        int32 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *RequestAllPaginado) Reset() {
	*x = RequestAllPaginado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAllPaginado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAllPaginado) ProtoMessage() {}

func (x *RequestAllPaginado) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAllPaginado.ProtoReflect.Descriptor instead.
func (*RequestAllPaginado) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{18}
}

func (x *RequestAllPaginado) GetTamanhoPagina() int32 {
	if x != nil {
		return x.TamanhoPagina
	}
	return 0
}

func (x *RequestAllPaginado) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type RequestEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RequestEmail) Reset() {
	*x = RequestEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmail) ProtoMessage() {}

func (x *RequestEmail) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmail.ProtoReflect.Descriptor instead.
func (*RequestEmail) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{19}
}

func (x *RequestEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RequestAlterarSenhaAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenhaNova string `protobuf:"bytes,2,opt,name=senhaNova,proto3" json:"senhaNova,omitempty"`
}

func (x *RequestAlterarSenhaAdmin) Reset() {
	*x = RequestAlterarSenhaAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAlterarSenhaAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAlterarSenhaAdmin) ProtoMessage() {}

func (x *RequestAlterarSenhaAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAlterarSenhaAdmin.ProtoReflect.Descriptor instead.
func (*RequestAlterarSenhaAdmin) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{20}
}

func (x *RequestAlterarSenhaAdmin) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestAlterarSenhaAdmin) GetSenhaNova() string {
	if x != nil {
		return x.SenhaNova
	}
	return ""
}

type RequestAlterarSenhaUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenhaAntiga string `protobuf:"bytes,2,opt,name=senhaAntiga,proto3" json:"senhaAntiga,omitempty"`
	SenhaNova   string `protobuf:"bytes,3,opt,name=senhaNova,proto3" json:"senhaNova,omitempty"`
}

func (x *RequestAlterarSenhaUsuario) Reset() {
	*x = RequestAlterarSenhaUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAlterarSenhaUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAlterarSenhaUsuario) ProtoMessage() {}

func (x *RequestAlterarSenhaUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAlterarSenhaUsuario.ProtoReflect.Descriptor instead.
func (*RequestAlterarSenhaUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{21}
}

func (x *RequestAlterarSenhaUsuario) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestAlterarSenhaUsuario) GetSenhaAntiga() string {
	if x != nil {
		return x.SenhaAntiga
	}
	return ""
}

func (x *RequestAlterarSenhaUsuario) GetSenhaNova() string {
	if x != nil {
		return x.SenhaNova
	}
	return ""
}

type ResponseTokenResetSenha struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResponseTokenResetSenha) Reset() {
	*x = ResponseTokenResetSenha{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTokenResetSenha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTokenResetSenha) ProtoMessage() {}

func (x *ResponseTokenResetSenha) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTokenResetSenha.ProtoReflect.Descriptor instead.
func (*ResponseTokenResetSenha) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{22}
}

func (x *ResponseTokenResetSenha) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_modelos_proto protoreflect.FileDescriptor

var file_modelos_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xde, 0x02, 0x0a, 0x0e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x64, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x69, 0x64, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x76,
	0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x28,
	0x0a, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68,
	0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74, 0x75, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x12, 0x28, 0x0a, 0x0f,
	0x73, 0x65, 0x6e, 0x68, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x41, 0x74, 0x75, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63,
	0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x63, 0x61, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74, 0x75,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x22, 0x87, 0x01,
	0x0a, 0x09, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74,
	0x69, 0x76, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64,
	0x6f, 0x45, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x75, 0x61, 0x6c,
	0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x22, 0x69, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x70,
	0x65, 0x72, 0x66, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x61, 0x6f, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x6f,
	0x65, 0x73, 0x22, 0xee, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x53, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x64, 0x6f, 0x45, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x75,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x6e,
	0x68, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x64, 0x61, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x50,
	0x65, 0x72, 0x66, 0x69, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x6f, 0x52, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x6f, 0x12, 0x3c, 0x0a, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x6f, 0x52, 0x0e, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x6f, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52,
	0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66,
	0x69, 0x6c, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x65,
	0x72, 0x66, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c,
	0x12, 0x40, 0x0a, 0x10, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x6f,
	0x52, 0x10, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x6f, 0x73, 0x12, 0x40, 0x0a, 0x10, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x6f, 0x52, 0x10, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x6f, 0x73, 0x22, 0x22, 0x0a, 0x0a, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x65, 0x6e, 0x68, 0x61, 0x22, 0x65, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x11, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x4e,
	0x6f, 0x76, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x68, 0x61,
	0x4e, 0x6f, 0x76, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x61, 0x7a, 0x69, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x64, 0x6f, 0x22, 0x5f, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68, 0x6f, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68, 0x6f,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x71,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68, 0x6f, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x61, 0x6d, 0x61,
	0x6e, 0x68, 0x6f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x22, 0x30, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x72, 0x6f, 0x78, 0x69, 0x6d, 0x6f, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x6f, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68, 0x6f, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68,
	0x6f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x6d, 0x4d, 0x61,
	0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69,
	0x73, 0x22, 0x52, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x64, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x6d, 0x61, 0x6e,
	0x68, 0x6f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x74, 0x61, 0x6d, 0x61, 0x6e, 0x68, 0x6f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x48, 0x0a, 0x18, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x72, 0x53, 0x65, 0x6e,
	0x68, 0x61, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x68, 0x61,
	0x4e, 0x6f, 0x76, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x68,
	0x61, 0x4e, 0x6f, 0x76, 0x61, 0x22, 0x6c, 0x0a, 0x1a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x61, 0x72, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x41, 0x6e, 0x74, 0x69,
	0x67, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x41,
	0x6e, 0x74, 0x69, 0x67, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x4e, 0x6f,
	0x76, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x4e,
	0x6f, 0x76, 0x61, 0x22, 0x2f, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x69, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_modelos_proto_rawDescOnce sync.Once
	file_modelos_proto_rawDescData = file_modelos_proto_rawDesc
)

func file_modelos_proto_rawDescGZIP() []byte {
	file_modelos_proto_rawDescOnce.Do(func() {
		file_modelos_proto_rawDescData = protoimpl.X.CompressGZIP(file_modelos_proto_rawDescData)
	})
	return file_modelos_proto_rawDescData
}

var file_modelos_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_modelos_proto_goTypes = []any{
	(*UsuarioExterno)(nil),             // 0: grpc.UsuarioExterno
	(*Perfil)(nil),                     // 1: grpc.Perfil
	(*Permissao)(nil),                  // 2: grpc.Permissao
	(*PerfilPermissoes)(nil),           // 3: grpc.PerfilPermissoes
	(*UsuarioInterno)(nil),             // 4: grpc.UsuarioInterno
	(*UsuarioPerfis)(nil),              // 5: grpc.UsuarioPerfis
	(*PerfilUsuarios)(nil),             // 6: grpc.PerfilUsuarios
	(*EmailReset)(nil),                 // 7: grpc.EmailReset
	(*LoginUsuario)(nil),               // 8: grpc.LoginUsuario
	(*RetornoLoginUsuario)(nil),        // 9: grpc.RetornoLoginUsuario
	(*ResetSenhaUsuario)(nil),          // 10: grpc.ResetSenhaUsuario
	(*RequestVazio)(nil),               // 11: grpc.RequestVazio
	(*RequestId)(nil),                  // 12: grpc.RequestId
	(*ResponseBool)(nil),               // 13: grpc.ResponseBool
	(*RequestNome)(nil),                // 14: grpc.RequestNome
	(*RequestCodReserva)(nil),          // 15: grpc.RequestCodReserva
	(*RequestDocumento)(nil),           // 16: grpc.RequestDocumento
	(*Meta)(nil),                       // 17: grpc.Meta
	(*RequestAllPaginado)(nil),         // 18: grpc.RequestAllPaginado
	(*RequestEmail)(nil),               // 19: grpc.RequestEmail
	(*RequestAlterarSenhaAdmin)(nil),   // 20: grpc.RequestAlterarSenhaAdmin
	(*RequestAlterarSenhaUsuario)(nil), // 21: grpc.RequestAlterarSenhaUsuario
	(*ResponseTokenResetSenha)(nil),    // 22: grpc.ResponseTokenResetSenha
}
var file_modelos_proto_depIdxs = []int32{
	1, // 0: grpc.PerfilPermissoes.perfil:type_name -> grpc.Perfil
	2, // 1: grpc.PerfilPermissoes.permissoes:type_name -> grpc.Permissao
	4, // 2: grpc.UsuarioPerfis.usuarioInterno:type_name -> grpc.UsuarioInterno
	0, // 3: grpc.UsuarioPerfis.usuarioExterno:type_name -> grpc.UsuarioExterno
	1, // 4: grpc.UsuarioPerfis.perfis:type_name -> grpc.Perfil
	1, // 5: grpc.PerfilUsuarios.perfil:type_name -> grpc.Perfil
	4, // 6: grpc.PerfilUsuarios.usuariosInternos:type_name -> grpc.UsuarioInterno
	0, // 7: grpc.PerfilUsuarios.usuariosExternos:type_name -> grpc.UsuarioExterno
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_modelos_proto_init() }
func file_modelos_proto_init() {
	if File_modelos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modelos_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UsuarioExterno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Perfil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Permissao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PerfilPermissoes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UsuarioInterno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UsuarioPerfis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PerfilUsuarios); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EmailReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LoginUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RetornoLoginUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ResetSenhaUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RequestVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RequestId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RequestNome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RequestCodReserva); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RequestDocumento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RequestAllPaginado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RequestEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*RequestAlterarSenhaAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*RequestAlterarSenhaUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseTokenResetSenha); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modelos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modelos_proto_goTypes,
		DependencyIndexes: file_modelos_proto_depIdxs,
		MessageInfos:      file_modelos_proto_msgTypes,
	}.Build()
	File_modelos_proto = out.File
	file_modelos_proto_rawDesc = nil
	file_modelos_proto_goTypes = nil
	file_modelos_proto_depIdxs = nil
}
